### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Faikert** [uyras/QtViewer#1]
В меню "Вид" кнопка под хоткеем F5 называется обовить
![image](https://user-images.githubusercontent.com/58805800/70693262-d7760000-1d08-11ea-83fc-76ac83fa15c4.png)

**Comment by uyras** [comment]
https://github.com/uyras/QtViewer/commit/9ec347a8efa334f6b543cc903e5360584b8fe42a 

В коде поправил. В бинарниках появится в следующем релизе. Спасибо.
